[project]
name = "zangy"
repository = "https://github.com/Gelbpunkt/zangy"

[build-system]
requires = ["maturin>=0.11,<0.12"]
build-backend = "maturin"

[tool.maturin]
manylinux = "Linux"
strip = true
