[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Z", "mir-opt-level=3", "-Z", "unsound-mir-opts", "-C", "target-cpu=native", "-Z", "tune-cpu=native", "-Z", "strip=symbols"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=-crt-static"]

[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "target-feature=-crt-static"]
