name: Python package build

on:
  push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Build manylinux Python wheels
        run: |
          podman build -t maturin:latest .
          podman run --rm -it -e CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu -v $(pwd):/io maturin:latest build -f --release --strip --compatibility manylinux_2_28
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux
          path: 'target/wheels/*-manylinux*.whl'

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: cargo, rustc, rust-src
      - name: Install maturin
        run: |
          pip install maturin
      - name: Build Python wheels
        run: |
          maturin build --release --strip
        env:
          CARGO_BUILD_TARGET: x86_64-pc-windows-msvc
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-windows
          path: 'target/wheels/*.whl'
